[TypedPropertyRector] Do not refactor to `iterable` property type (#6196)
# Failing Test for TypedPropertyRector

Based on https://getrector.org/demo/3a8fc4f5-898d-4fb4-8ed3-99dc8312df77

```
Fatal error: Cannot use iterable as iterable because 'iterable' is a special class name
```